### ISSUE TITLE
Add support for instrumenting `ExecutorService`

### ISSUE THREAD

**Issue by jkschneider** [spring-projects/spring-metrics#15]
Required by #1

**Comment by checketts** [comment]
Unfortunately the instrumentation returns a wrapped executor service, but in the case of the sample app the `TaskPoolTaskExecutor` already is referencing its executor service and it isn't apparent how we can replace the existing one with the metrics one.

While the current solution will be useful for some cases, I think we might want the executor service monitor to merely report on the active threads and queue depth of the existing executor service, and have it set task decorators automatically to get the durations.  

Should we reopen this issue or create a new one specific to `monitoring existing ExecutorServices`?
