### ISSUE TITLE
Add Histogram support

### ISSUE THREAD

**Issue by jkschneider** [spring-projects/spring-metrics#18]
The history of Dropwizard and Prometheus client-side quantile computation is too much to ignore.

**Comment by checketts** [comment]
The prometheus implementation is essentially just a grouping of counters, so that method could be used if spectator doesn't support histograms.

**Comment by jkschneider** [comment]
Spectator has support with specializations of timer and distribution summary: `BucketTimer` and `BucketDistributionSummary`. Even more specialized is `PercentileTimer` and `PercentileDistributionSummary`.

**Comment by jkschneider** [comment]
Near equilavent of Prometheus' server-side `histogram_buckets` is Atlas' [percentiles](https://github.com/Netflix/atlas/wiki/math-percentiles).

**Comment by jkschneider** [comment]
Spectator bucket meters are non-cumulative, determined on a per-sample basis by `LongFunction<String>`. Prometheus histograms are cumulative, buckets are always mathy.
