### ISSUE TITLE
summary in PrometheusMeterRegistry.timer() does not respect tags

### ISSUE THREAD

**Issue by mlausch1963** [spring-projects/spring-metrics#27]
In PrometheusMeterRegistry.timer() the summary metric is looked up using **only** the metrics name.
around line 100 `` collectorMap.computeIfAbsent(name , ...)``.
This has the following effects:
  - the labels for the summary are the labels of the first timer.
  - timing of requests which cause an error (status >= 400) are conflated with timing of successful requests. Failing requests usually do not take as much time as working requests and therefore the statistic is skewed.
  - timing of all requests, no matter how expensive they are are mashed together. They should be separated by the URL path (at least).

**Comment by checketts** [comment]
This isn't due to the `collectorMap.compueIfAbsent` as much as the fact that `CustomPrometheusSummmary` departs from the `child`  semantics of other metrics since the `meterMap.computeIfAbsent` (which uses the `id` (name and tags)) to calculate should take tags into account.

**Comment by mlausch1963** [comment]
Maybe i'm missing something important but this makes the summary kind of useless because it mixes up all requests from all endpoints and the labels do not contain any useful information. 
The timer from the meterMap is also constructed without any label info, but just proxies the record() calls to the summary. 
I instrumented the sample spring webmvc application and the http_server_requests metrics i see in the /prometheus output is:
```
# HELP http_server_requests 
# TYPE http_server_requests summary
http_server_requests_count{method="GET",uri="root",exception="None",status="200",} 4.0
http_server_requests_sum{method="GET",uri="root",exception="None",status="200",} 0.331367266
```
after adding/listing/modifing messages which hit different endpoints.

**Comment by checketts** [comment]
Sorry, I didn't mean to mislead. This is definitely a bug. I was just recording the root cause for how we can fix it so I don't end up repeating same analysis later.

**Comment by jkschneider** [comment]
Thanks again for the report @mlausch1963.
