### ISSUE TITLE
Support adding CustomMeters to MeterRegistry

### ISSUE THREAD

**Issue by checketts** [spring-projects/spring-metrics#30]
This will parallel the `CustomCollector` concept in Prometheus.

Proposal:
* Add `register(MeterReporter)` to `MetricRegistry`
* `MeterReporter`'s interface will return a list of metrics that will be converted to the underlying MeterRegistry's metrics. The important thing to keep in mind is that a `MeterReporter` will be able to report multiple meters.

**Comment by checketts** [comment]
This feature solution will be a better all around solution to #29 (though I suspect the binder approach will still be useful elsewhere)

**Comment by checketts** [comment]
I'm going to work this now

**Comment by jkschneider** [comment]
Still a ways to go. Need a facility to make it easier to create `Measurement`s each of which generally inherit the name and tags of its parent and add another tag like `statistic`.
