### ISSUE TITLE
Change `package` constructor to `public` on Simple* Meters

### ISSUE THREAD

**Issue by Camelion** [spring-projects/spring-metrics#41]
`SimpleCounter`, `SimpleGauge`, etc.. currently can't  be reused in `spring-metrics` extensions, because their constructor is only package-visible. 
I wrote [simple extension](https://github.com/Camelion/spring-clickhouse-metrics/tree/2.0.0) on top of `spring-metrics` for use ClickHouse database as storage for metrics, and most of Meter classes is duplicates of Simple*Meter classes. I think some custom extensions may reuse code of `Simple` meters as is. Thanks!

**Comment by jkschneider** [comment]
Thanks for bringing ClickHouse to my attention. I'd like to consider this as a first-class support target.

My main concern is the flattening of tags to a hierarchical format [here](https://github.com/Camelion/spring-clickhouse-metrics/blob/2.0.0/src/main/java/ru/jts/spring/clickhouse/metrics/ClickHouseMetricWriter.java#L89-L90), which I understand helps keep the schema simple.

Would a table-per-metric-name approach be prohibitive? Such an approach would allow you to build a schema that stored tags in individual columns. This assumes that possible tag keys are known at the first export when the schema is created, but this is not without precedent in monitoring systems (e.g. Prometheus has this constraint).

**Comment by Camelion** [comment]
Thanks for fixing Simple classes!

Currently ClickHouse doesn't support storing values in hierarchical format, but it's possible to store all tags as `Array` type [described here](https://clickhouse.yandex/docs/en/data_types/array.html) and prebuilt several views on top of them, e.g. one view per type: `application_counter_view, application_gauge_view,  application_timer_view, etc..`

Or use `Array` with tags directly without view, but in some complex syntax:
```sql
select timestamp, metric, value
from application_metrics 
where tags[indexOf(tags, 'type') + 1] = 'Counter';
```
