### ISSUE TITLE
Support pass-through without aggregation?

### ISSUE THREAD

**Issue by robinst** [spring-projects/spring-metrics#44]
Hey! I was wondering if you plan on supporting metrics that are not aggregated, but instead are sent directly to a daemon as they are recorded.

Background: In our setup, we use a `dogstatsd` like daemon that runs on every instance. It accepts metrics directly via UDP, aggregates them and then forwards to Datadog, as described here: http://docs.datadoghq.com/guides/dogstatsd/

In that case, the daemon already does aggregation. So if the library we use *also* does aggregation, we end up with metrics that are not as useful as they could be.

I see that the basic interfaces such as [`Timer`](https://github.com/spring-projects/spring-metrics/blob/master/src/main/java/org/springframework/metrics/instrument/Timer.java#L30) would be generic enough to allow an implementation to forward as soon as the method is called. But there's also some parts of it that seem only useful for aggregation, such as [`totalTime`](https://github.com/spring-projects/spring-metrics/blob/master/src/main/java/org/springframework/metrics/instrument/Timer.java#L89).

As the library seems to not yet be in a released state, it might be a good point in time to consider this use case. Thanks!

(I'm currently looking at [java-dogstatsd-client](https://github.com/DataDog/java-dogstatsd-client) because it does what we want in that it directly sends to `dogstatsd`. But I'm also considering adding some bits on top such as support for `@Timed`.)

**Comment by jkschneider** [comment]
@robinst Simple answer up front is YES. Whether metrics are aggregated or not is dependent on the `MeterRegistry` implementation (e.g. the Prometheus implementation does not do aggregation). Two things about Datadog:

I originally looked at java-dogstatsd-client when I went to implement Datadog support, but concluded that I could achieve the same thing by aggregating and shipping metrics directly to the Datadog API. This should yield the same result as `datadogstatsd`, and have the added benefit of not requiring you to install an agent alongside your services.

That said, I do intend on adding a general statsd `MeterRegistry` as well. To do this well, somehow that registry will have to be configured or be aware of the many specializations of statsd that exist in the wild, including Datadog's.

I'd love to hear your feedback on whether you think the direct-to-API approach is beneficial to you, or if there is a reason you need to stick with dogstatsd?

**Comment by robinst** [comment]
> To do this well, somehow that registry will have to be configured or be aware of the many specializations of statsd that exist in the wild, including Datadog's.

Yes! Sounds like you've given this some thought already, which is good to hear. Is there anything that I could help out with already?

> I'd love to hear your feedback on whether you think the direct-to-API approach is beneficial to you, or if there is a reason you need to stick with dogstatsd?

I'm pretty sure that we are not going to switch to that approach. We have hundreds of microservices (in different languages) that all have the same base setup. One of the pieces of that is that there's a `statsd` hostname that's accessible from the microservice. It sends the metrics there directly, and it takes care of auth and aggregation. It also adds some tags based on the environment, etc, and it works the same way for all the languages/frameworks. Hope that helps :).

**Comment by jkschneider** [comment]
Thanks for sharing your setup. I was really just looking for a real world justification for supporting dogstatsd independently.

**Comment by robinst** [comment]
Cool. So I think we can close this issue and I'll just watch #45. Thank you!

By the way, do you have a rough idea when this library will no longer be considered "early work"? I considered to start using it already but if the API might still change a lot from what it is currently, then I'd rather wait a bit longer.

**Comment by jkschneider** [comment]
@robinst The project is undergoing a split where the core instrumentation facade is being rebranded to Micrometer (`io.micrometer:micrometer-core` with correlated package name changes). The spring-specific bits are going both directly into Spring Boot 2.0 (we think) and into a `spring-boot-legacy-micrometer`-ish module which will drop down dimensional metrics support on Spring Boot 1.X.

Once the code is split, I'll do a pre-1.0 release on Micrometer, and its API is relatively set with mainly additive changes going forward (e.g. global tagging, support for additional monitoring systems). With any luck, Boot 2.0's M3 release in a week will have a dependency on this pre-1.0 release of Micrometer, so the API will really need to be pretty set.

Hopefully that gives you an understanding of the big picture!

**Comment by robinst** [comment]
Sounds awesome! Looking forward to a nice clean set of interfaces that support tags (and where the package name match the group ID 😜).
