### ISSUE TITLE
PrometheusMetricRegistry doesn't actually register metrics with its internal CollectorRegistry

### ISSUE THREAD

**Issue by checketts** [spring-projects/spring-metrics#6]
There are 2 options:

* `PrometheusMetricRegistry` could override `Register` from its parent class and add the metric to the internal registry. (Simplest, but could cause trouble with multiple registrations, so code will need to check/handle that)
* The `PrometheusMetricRegistry` could implement the Prometheus `Collector` interface itself and only register itself as the single collector that Prometheus call to fetch metrics from.

While the second option will be slightly more complex, I think it will give us the ability to shim/protect against any Prometheus/Spring Metrics differences.

**Comment by jkschneider** [comment]
@checketts See the comment on 676ff5a. I'm not married to the current solution.

**Comment by jkschneider** [comment]
As of e2d873abd70c05ab4d6e5e9697dbe952f446fcb1, we are now registering every `Collector` that we build, but are conditionally building `Collectors` only if we haven't already built one with the same name/tag combination previously.
